name: Continuous Delivery

on: push

jobs:
  static-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch_depth: 0

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: "nextjournal"
          service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          export_default_credentials: true

      - name: Install java
        uses: actions/setup-java@v1
        with:
          java-version: '18'

      - name: Install clojure
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: '1.11.1.1208'
          bb: '1.2.174'

      - name: maven cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2
            ~/.gitlibs
            ~/.deps.clj
          key: ${{ runner.os }}-maven-build-${{ hashFiles('deps.edn') }}

      - name: npm cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: shadow-cljs compiler cache
        uses: actions/cache@v2
        with:
          path: .shadow-cljs
          key: ${{ runner.os }}-shadow-cljs-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-shadow-cljs-

      - name: Install npm dependencies with yarn
        run: yarn install

      - name: Install SSH key and start ssh-agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.NEXTJOURNAL_CI_SSH_KEY }}

      - name: Compile ClojureScript (snapshot build)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bb release:cljs

      - name: Compile CSS
        run: bb build:css

      - name: Build Notebooks
        run: bb build:devdocs

      - name: Copy Asseets
        run: bb build:copy-assets

      - name: Store in CAS
        run: echo "cas_url=$(bb devdocs:cas)" >> $GITHUB_ENV

      - name: Add status flag to the devcards build
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'Snapshot build'
          description: 'Ready'
          state: 'success'
          sha: ${{github.event.pull_request.head.sha || github.sha}}
          target_url: "${{ env.cas_url }}"
